const API="https://ypedqbffumjwccqmgauo.supabase.co/functions/v1/equal-world-api-v2";
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,o={}){const r=await fetch(`${API}/${path}`,{headers:{"Content-Type":"application/json",...(o.headers||{})},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
$("tracking-form").onsubmit=async e=>{e.preventDefault();$("tracking-result").innerHTML="<p>Looking up shipment…</p>";try{const d=await api("track?code="+encodeURIComponent($("tracking-code").value.trim()));const s=d.shipment;$("tracking-result").innerHTML=`<div class="tracking-card"><h3>${esc(s.tracking_code)}</h3><p><b>Status:</b> ${esc(s.status)}</p><p><b>Route:</b> ${esc(s.origin)} → ${esc(s.destination)}</p><p><b>Service:</b> ${esc(s.service)}</p><p><b>Estimated delivery:</b> ${esc(s.estimated_delivery||"To be confirmed")}</p>${(d.events||[]).map(x=>`<div class="event"><b>${esc(x.status)}</b> — ${esc(x.location)}<br><small>${esc(x.description||"")} · ${esc(x.event_time)}</small></div>`).join("")}</div>`}catch(x){$("tracking-result").innerHTML=`<p class="error">${esc(x.message)}</p>`}};
let sid=sessionStorage.getItem("ews_chat_session_id"),token=sessionStorage.getItem("ews_visitor_token"),poll;
function msg(m){return `<div class="msg ${m.sender==="visitor"?"mine":"agent"}"><span>${esc(m.message)}</span><small>${new Date(m.sent_at).toLocaleTimeString()}</small></div>`}
async function load(){if(!sid||!token)return;try{const d=await api("chat_messages?session_id="+encodeURIComponent(sid),{headers:{Authorization:"Bearer "+token}});$("chat-messages").innerHTML=(d.messages||[]).map(msg).join("");$("chat-messages").scrollTop=99999}catch{}}
$("chat-toggle").onclick=()=>{$("chat-panel").hidden=false;$("chat-toggle").hidden=true;load()},$("chat-close").onclick=()=>{$("chat-panel").hidden=true;$("chat-toggle").hidden=false};
if(sid&&token){$("chat-start-form").hidden=true;$("chat-message-form").hidden=false;poll=setInterval(load,5000);load()}
$("chat-start-form").onsubmit=async e=>{e.preventDefault();try{const d=await api("chat_start",{method:"POST",body:JSON.stringify({name:$("chat-name").value.trim(),email:$("chat-email").value.trim()})});sid=d.session_id;token=d.visitor_token;sessionStorage.setItem("ews_chat_session_id",sid);sessionStorage.setItem("ews_visitor_token",token);$("chat-start-form").hidden=true;$("chat-message-form").hidden=false;await load();clearInterval(poll);poll=setInterval(load,5000)}catch(x){alert(x.message)}};
$("chat-message-form").onsubmit=async e=>{e.preventDefault();const i=$("chat-message"),v=i.value.trim();if(!v)return;try{await api("chat_message",{method:"POST",headers:{Authorization:"Bearer "+token},body:JSON.stringify({session_id:sid,message:v})});i.value="";await load()}catch(x){alert(x.message)}};
